{% set version = "4.0.1" %}

package:
  name: flask-cors
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/flask-cors/flask_cors-{{ version }}.tar.gz
  sha256: eeb69b342142fdbf4766ad99357a7f3876a2ceb77689dc10ff912aac06c389e4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - flask >=0.9
    - python >=3.8

test:
  requires:
    - pip
  imports:
    - flask_cors
    - flask_cors.core
    - flask_cors.decorator
    - flask_cors.extension
    - flask_cors.version
  commands:
    - pip check

about:
  home: https://github.com/corydolphin/flask-cors
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: A Flask extension adding a decorator for CORS support

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
    - bollwyvl
