{% set name = "Flask-Cors" %}
{% set version = "3.0.9" %}
{% set bundle = "tar.gz" %}
{% set hash = "6bcfc100288c5d1bcb1dbb854babd59beee622ffd321e444b05f24d6d58466b8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip

  run:
    - python
    - flask >=0.9
    - six

test:
  imports:
    - flask_cors
    - flask_cors.core
    - flask_cors.decorator
    - flask_cors.extension
    - flask_cors.version

about:
  home: https://github.com/corydolphin/flask-cors
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: A Flask extension adding a decorator for CORS support
  doc_url: http://flask-cors.corydolphin.com/en/latest/
  dev_url: https://github.com/corydolphin/flask-cors

extra:
  recipe-maintainers:
    - pmlandwehr
