{% set version = "5.0.0" %}

package:
  name: flask-cors
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/f/flask-cors/flask_cors-{{ version }}.tar.gz
  sha256: 5aadb4b950c4e93745034594d9f3ea6591f734bb3662e16e255ffbf5e89c88ef

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - flask >=0.9
    - python >={{ python_min }}

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - flask_cors
    - flask_cors.core
    - flask_cors.decorator
    - flask_cors.extension
    - flask_cors.version
  commands:
    - pip check

about:
  home: https://github.com/corydolphin/flask-cors
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: A Flask extension adding a decorator for CORS support

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
    - bollwyvl
