# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "6.0.4"
  python_check_max: "3.14"

package:
  name: flask-cors
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/f/flask-cors/flask_cors-${{ version }}.tar.gz
    sha256: cf3db91a0874aecde0a276565bf4adf4a458edcfd42e668fb0a260549f129317
  - url: https://raw.githubusercontent.com/corydolphin/flask-cors/refs/tags/${{ version }}/LICENSE
    sha256: 134a20d852c0cf9e0f3c228767921b76f4bfc4af4a2fc7c4cc90f6b4fd407b5c

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
    - setuptools-scm
  run:
    - flask >=0.9
    - python >=${{ python_min }}
    - werkzeug >=0.7

tests:
  - python:
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*
      imports:
        - flask_cors
        - flask_cors.core
        - flask_cors.decorator
        - flask_cors.extension
  - requirements:
      run:
        - python ${{ python_min }}.*
        - pytest-cov
    files:
      source:
        - tests/
    script:
      - python -c "from importlib import metadata as md; v = md.version('flask-cors'); print(v); assert v == '${{ version }}'"
      - coverage run --source=flask_cors --branch -m pytest -vv --tb=long --color=yes
      - coverage report --show-missing --skip-covered --fail-under=95

about:
  license: MIT
  license_file: LICENSE
  summary: A Flask extension adding a decorator for CORS support
  homepage: https://github.com/corydolphin/flask-cors

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
    - bollwyvl
