# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 5.0.1

package:
  name: flask-cors
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/f/flask-cors/flask_cors-${{ version }}.tar.gz
  sha256: 6ccb38d16d6b72bbc156c1c3f192bc435bfcc3c2bc864b2df1eb9b2d97b2403c

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - flask >=0.9
    - python >=${{ python_min }}
    - werkzeug >=0.7

tests:
  - python:
      pip_check: true
      python_version: ${{ python_min }}.*
      imports:
        - flask_cors
        - flask_cors.core
        - flask_cors.decorator
        - flask_cors.extension
        - flask_cors.version

about:
  license: MIT
  license_file: LICENSE
  summary: A Flask extension adding a decorator for CORS support
  homepage: https://github.com/corydolphin/flask-cors

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
    - bollwyvl
